docker:
    path: .
id: 24ea9ef9-40da-4b34-82ed-c6da2b3c98f9
ide:
    filename: ide.yaml
name: stackoverflow_etl
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags
    version: "2"
